name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.5.2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 修改为稳定的 Node 20 版本
          cache: 'pnpm'

      # Vite 项目标准构建流程
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        run: pnpm build  # 执行你的 Vite 打包命令
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # Vite 默认打包生成的目录就是 dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4